# Generated by Django 3.1.1 on 2021-02-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210211_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='c_file',
            field=models.FileField(default='.', upload_to='Citywise-data/'),
        ),
    ]
