# Generated by Django 3.1.1 on 2021-02-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ('c_name',)},
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.timestamp')),
                ('e_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('e_url', models.URLField()),
                ('img_url', models.URLField()),
                ('genre', models.CharField(max_length=50)),
                ('city', models.ManyToManyField(to='app.Cities')),
            ],
            options={
                'ordering': ('title',),
            },
            bases=('app.timestamp',),
        ),
    ]
